spring.application.name=ConnectX
# Server Configuration
server.port=${PORT:8080}
# Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/connectX_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.url=${url}
#spring.datasource.username=root
spring.datasource.username=${username}
#spring.datasource.password=gumgum
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
#spring.mail.username=uchihamadara.24121950@gmail.com
#spring.mail.password=bssu jfmc jned mgfq

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=./uploads

# CORS Configuration
app.cors.allowed-origins=http://localhost:3000

# WebSocket Configuration
websocket.allowed-origins=http://localhost:3000